"""Init

Revision ID: 1d85c976411d
Revises: 
Create Date: 2025-02-10 21:40:37.561777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d85c976411d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_category_id_key', 'books', type_='unique')
    op.drop_constraint('books_category_id_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('books_category_id_fkey', 'books', 'categories', ['category_id'], ['id'])
    op.create_unique_constraint('books_category_id_key', 'books', ['category_id'])
    # ### end Alembic commands ###
