"""Fix books table

Revision ID: 295c60acfeac
Revises: e8bdad8e5e36
Create Date: 2025-01-29 15:14:58.246695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '295c60acfeac'
down_revision: Union[str, None] = 'e8bdad8e5e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_m2m_shelf_signature')
    op.drop_table('book_m2m_publisher')
    op.drop_table('cover_pages')
    op.add_column('books', sa.Column('title_id', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('publisher_id', sa.String(length=50), nullable=True))
    op.alter_column('books', 'shelf_signature_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_constraint('books_cover_page_id_key', 'books', type_='unique')
    op.create_unique_constraint(None, 'books', ['publisher_id'])
    op.create_unique_constraint(None, 'books', ['title_id'])
    op.drop_constraint('books_cover_page_id_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'titles', ['title_id'], ['id'])
    op.create_foreign_key(None, 'books', 'publishers', ['publisher_id'], ['id'])
    op.drop_column('books', 'cover_page_id')
    op.drop_column('books', 'title')
    op.alter_column('publishers', 'publication_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publishers', 'publication_year',
               existing_type=sa.String(length=150),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.add_column('books', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('cover_page_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_cover_page_id_fkey', 'books', 'cover_pages', ['cover_page_id'], ['id'])
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_constraint(None, 'books', type_='unique')
    op.create_unique_constraint('books_cover_page_id_key', 'books', ['cover_page_id'])
    op.alter_column('books', 'shelf_signature_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('books', 'publisher_id')
    op.drop_column('books', 'title_id')
    op.create_table('cover_pages',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('cover_pages_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('cover_page', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cover_pages_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('book_m2m_publisher',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('publisher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='book_m2m_publisher_book_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], name='book_m2m_publisher_publisher_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='book_m2m_publisher_pkey')
    )
    op.create_table('book_m2m_shelf_signature',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shelf_signature_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='book_m2m_shelf_signature_book_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shelf_signature_id'], ['shelf_signatures.id'], name='book_m2m_shelf_signature_shelf_signature_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='book_m2m_shelf_signature_pkey')
    )
    # ### end Alembic commands ###
