"""add unique constraint to books

Revision ID: 3832966aee9a
Revises: 1d85c976411d
Create Date: 2025-03-03 21:35:30.221969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3832966aee9a'
down_revision: Union[str, None] = '1d85c976411d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_publisher_id_key', 'books', type_='unique')
    op.drop_constraint('books_shelf_signature_id_key', 'books', type_='unique')
    op.create_unique_constraint(None, 'isbn', ['isbn_name'])
    op.create_unique_constraint(None, 'titles', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'titles', type_='unique')
    op.drop_constraint(None, 'isbn', type_='unique')
    op.create_unique_constraint('books_shelf_signature_id_key', 'books', ['shelf_signature_id'])
    op.create_unique_constraint('books_publisher_id_key', 'books', ['publisher_id'])
    # ### end Alembic commands ###
